### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by DevLaTron** [fractalwagmi/unity-sdk#6]
Adding a package.json would allow people to link up the github directly into their Unity Packamge Manager:

Basic example:

{
    "name": "is.fractal.unity.sdk",    
    "version": "1.0.0",
    "displayName": "Fractal Unity SDK",
    "description": "Someverynicedescription here",
    "keywords": [
        "integrate",
        "tools",
        "crypto",
    ],
    "author": {
        "name": "Fractal",
        "email": "someemail",
        "url": "somewebsite"
    }
}

For Details see: https://docs.unity3d.com/Manual/upm-manifestPkg.html

**Comment by oliexe** [comment]
Added package manifest file. Thanks
